stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: blueforest/attribut:1.2.1
      pushRemote: true
      registry: index.docker.io
timeout: 60
